location: gitman-repositories/
sources:
  - repo: https://github.com/imker25/samba_exporter.git
    name: samba_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
sources_locked:
  - repo: https://github.com/imker25/samba_exporter.git
    name: samba_exporter
    rev: 3b29a046510551c78f262802e04a007c3d3ed3d3
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
default_group: ""
groups:
  -
