---
title: Healthchecks
---
%%{ init : { "theme" : "default", "flowchart" : { "curve" : "linear" }}}%%

flowchart LR
    classDef default fill:#00000000,stroke:#00000000,stroke-width:0px;
    classDef component fill:#00000000,stroke:#aabbccff,stroke-width:2px;
    classDef section fill:#00000000,stroke:#aabbccff,stroke-width:3px;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    other_apps["<img src='../../../../icons/apps.png' style='min-width:80px;max-width:80px' /><br />Other<br />Apps"]

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        app("<img src='../../../../icons/healthchecks.png' style='min-width:80px;max-width:80px' /><br />Healthchecks")
        db_sync("<img src='../../../../icons/litestream.png' style='min-width:80px;max-width:80px' /><br />Litestream")

        class app component
        class certificate_manager component
        class db_sync component
        class http_proxy component
        class socket_proxy component

        app ~~~ db_sync
        socket_proxy <--->|:80,443| http_proxy <--->|:8000| app
        http_proxy -..-|fs| certificate_manager
        db_sync -..->|fs| app
    end
    class app_wrapper section

    s3_database["<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Minio"]

    home_network <-->|:80,443| socket_proxy
    other_apps -..->|cron status| app_wrapper
    other_apps ~~~~ socket_proxy
    db_sync -.->|send| s3_database
