---
title: Homelab Network
config:
    theme: dark
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef no_border stroke:#ffffff00,stroke-width:0px;

    internet("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/cloud.png' style='min-width:80px;max-width:80px' /></div>Internet")

    subgraph living_room["Living Room"]
        4g_modem("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/usb-wifi.png' style='min-width:80px;max-width:80px' /></div>4G Modem<br/>Huawei E3372")
        router("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/router.png' style='min-width:80px;max-width:80px' /></div>Router<br/>TP-Link ER605")
        switch_8_dumb("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/switch.png' style='min-width:80px;max-width:80px' /></div>Switch<br/>TP-Link SG108")
        switch_8_smart("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/switch.png' style='min-width:80px;max-width:80px' /></div>Switch<br/>TP-Link SG108E")
        raspberry_pi_4b_2gb("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/server-small.png' style='min-width:80px;max-width:80px' /></div>App Server<br/>Raspberry Pi 4B 2GB")
        odroid_h3("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/server-big.png' style='min-width:80px;max-width:80px' /></div>App Server<br/>Odroid H3")
        unifi_u6_mesh("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/wifi-ap.png' style='min-width:80px;max-width:80px' /></div>WiFi AP<br/>Unifi U6 Mesh")
        usb_ethernet_adapter("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/usb.png' style='min-width:80px;max-width:80px' /></div>USB Ethernet adapter<br/>")
        desklamp_1("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/lightbulb.png' style='min-width:80px;max-width:80px' /></div>DeskLamp<br/>Raspberry Pi Pico")
        desklamp_2("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/lightbulb.png' style='min-width:80px;max-width:80px' /></div>DeskLamp<br/>Raspberry Pi Pico")
        macbook_pro_2012("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/notebook.png' style='min-width:80px;max-width:80px' /></div>Storage Server<br/>MacBook Pro 2012")
    end

    subgraph kitchen["Kitchen"]
        switch_5_smart("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/switch.png' style='min-width:80px;max-width:80px' /></div>Switch<br/>TP-Link SG105E")
        raspberry_pi_3b("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/server-small.png' style='min-width:80px;max-width:80px' /></div>App Server<br/>Raspberry Pi 3B")
        raspberry_pi_3b_antenna("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/antenna.png' style='min-width:80px;max-width:80px' /></div>DVB-T Antenna")
        raspberry_pi_4b_4gb("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/server-small.png' style='min-width:80px;max-width:80px' /></div>App Server<br/>Raspberry Pi 4B 4GB")
        webcamera("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/webcamera.png' style='min-width:80px;max-width:80px' /></div>USB<br/>Webcam")
    end

    internet <--> 4g_modem <--> router
    router <--> switch_5_smart & switch_8_dumb & switch_8_smart
    switch_8_smart <--> raspberry_pi_4b_2gb & odroid_h3 & macbook_pro_2012 & unifi_u6_mesh & usb_ethernet_adapter & desklamp_1 & desklamp_2
    switch_5_smart <--> raspberry_pi_3b & raspberry_pi_4b_4gb
    raspberry_pi_3b ~~~ raspberry_pi_3b_antenna --> raspberry_pi_3b
    raspberry_pi_4b_4gb ~~~ webcamera --> raspberry_pi_4b_4gb

    living_room ~~~ kitchen
