---
title: Uptime Kuma
---
%%{ init : { "theme" : "default", "flowchart" : { "curve" : "linear" }}}%%

flowchart LR
    classDef default fill:#00000000,stroke:#00000000,stroke-width:0px;
    classDef component fill:#00000000,stroke:#aabbccff,stroke-width:2px;
    classDef section fill:#00000000,stroke:#aabbccff,stroke-width:3px;

    outside_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    other_apps["<img src='../../../../icons/apps.png' style='min-width:80px;max-width:80px' /><br />Other<br />Apps"]
    s3_database["<img src='../../../../icons/database.png' style='min-width:80px;max-width:80px' /><br />Minio"]

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        app("<img src='../../../../icons/uptime-kuma.png' style='min-width:80px;max-width:80px' /><br />Uptime<br />Kuma")
        script_backup("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/chromium+playwright.png' style='min-width:80px;max-width:80px' /><br />Backup<br />script")
        script_admin_setup("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/chromium+playwright.png' style='min-width:80px;max-width:80px' /><br />Admin<br />setup<br />script")

        class app component
        class certificate_manager component
        class http_proxy component
        class script_admin_setup component
        class script_backup component
        class socket_proxy component

        app ~~~ script_backup & script_admin_setup
        socket_proxy <--->|:80,443| http_proxy <--->|:3001| app
        script_backup & script_admin_setup -..->|use| app
        http_proxy -..-|fs| certificate_manager
    end
    class app_wrapper section

    outside_network <-->|:80,443| socket_proxy
    script_admin_setup ~~~ other_apps
    script_backup -.->|send backup| s3_database
    app -..->|check| other_apps
