app:
  name: DoneTick

apache:
  upstream-url:
    - path: /
      target: http://app:2021

favicons:
  default: /apple-touch-icon.png
  # ico: /favicon-32x32.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
