app:
  name: Grafana

apache:
  upstream-url:
    - path: /
      target: http://app:3000

favicons:
  default: /public/img/grafana_icon.svg
  # ico: /public/img/fav32.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    # TODO: Check if there is a /metrics endpoint
