apache:
  upstream-url:
    - path: /
      target: http://app:3000

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    # TODO: Check if there is a /metrics endpoint
