app:
  name: Docker Stats

apache:
  upstream-url:
    - path: /metrics
      target: http://app:9487
    - path: /
      target: http://file-server:8080

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer
  endpoints:
    - path: /metrics
      authentication:
        basic: prometheus

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
