app:
  name: Vaultwarden

apache:
  upstream-url:
    - path: /
      target: http://app:80

favicons:
  default: /images/apple-touch-icon.png
  # ico: /images/favicon-32x32.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
