app:
  name: Vaultwarden

apache:
  upstream-url:
    - path: /
      target: http://app:80

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
