location: gitman-repositories/
sources:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: main
    type: git
    params: --depth=1
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
sources_locked:
  - repo: https://github.com/letsencrypt/unbound_exporter.git
    name: unbound_exporter
    rev: 6ddcaa0c39cad04bfc8f56e804a47eacbb6502c6
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
    patches:
      -
default_group: ""
groups:
  -
