apache:
  upstream-url:
    - path: /
      target: http://app:1337

gatus:
  enabled: true
  # TODO: Add some endpoints

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
