app:
  name: Planka

apache:
  upstream-url:
    - path: /
      target: http://app:1337

favicons:
  default: /logo192.png
  # ico: /favicon.ico

gatus:
  enabled: true
  # TODO: Add some endpoints

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
