app:
  name: Template

apache:
  upstream-url:
    - path: /api/
      target: http://example.com:12345
    - path: /
      target: http://example.com:12345

gatus:
  enabled: true
  # TODO: Finish template

healthchecks:
  - slug: certificator
  - slug: app
    schedule: "* * * * *"

prometheus:
  enabled: true

  # Specify endpoints for monitoring
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth: # Optional, default: no authentication
        type: placeholder # Optional, default: "none", valid values: "basic", "bearer", or "none"
        # user: placeholder # Optional, only valid for basic-auth, default: "prometheus"
        # token: placeholder # Optional, only valid for bearer-auth
