app:
  name: ChangeDetection

apache:
  upstream-url:
    - path: /
      target: http://app:5000

gatus:
  enabled: true

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
