app:
  name: ChangeDetection

apache:
  upstream-url:
    - path: /
      target: http://app:5000

favicons:
  default: /static/favicons/apple-touch-icon.png
  # ico: /static/favicons/favicon-32x32.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
