app:
  name: Healthchecks

apache:
  upstream-url:
    - path: /
      target: http://app:8000

gatus:
  enabled: true
  endpoints:
    - path: /api/v3/status
    - path: /projects/${HEALTHCHECKS__PROMETHEUS_PROJECT}/metrics
      authentication:
        bearer: PROMETHEUS_TOKEN
    - path: /projects/${HEALTHCHECKS__PROMETHEUS_PROJECT}/metrics/${HEALTHCHECKS__PROMETHEUS_TOKEN}

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /projects/${<<APP>>__PROMETHEUS_PROJECT}/metrics
      auth:
        type: bearer
