x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./minio-server/Dockerfile
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/minio/data:/data:rw

  app-setup:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: template
    # Override:
    build:
      dockerfile: ./minio-client/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-setup
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app-setup.env
    image: ${DOCKER_COMPOSE_APP_NAME}-app-setup:1.0.0
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /home/homelab/.mc:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache-api:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-api
    environment:
      HOMELAB_CONTAINER_VARIANT: api
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-api:1.0.0
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache/api:/homelab/logs:rw

  apache-prometheus-exporter-api:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-api
    environment:
      HOMELAB_CONTAINER_VARIANT: api
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-api:1.0.0
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache-prometheus-exporter/api:/homelab/logs:rw

  apache-console:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-console
    environment:
      HOMELAB_CONTAINER_VARIANT: console
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-console:1.0.0
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache/console:/homelab/logs:rw

  apache-prometheus-exporter-console:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-console
    environment:
      HOMELAB_CONTAINER_VARIANT: console
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-console:1.0.0
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache-prometheus-exporter/console:/homelab/logs:rw

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
