x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./docker-images/minio-server/Dockerfile
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${DOCKER_COMPOSE_NETWORK_URL}/ui
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/minio/data:/data:rw

  app-setup:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/minio-client/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-setup
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app-setup.env
    image: ${DOCKER_COMPOSE_APP_NAME}-app-setup:1.0.0
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /home/homelab/.mc:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
