apache:
  upstream-url:
    - path: /ui/
      target: http://app:9001
    - path: /
      target: http://app:9000

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /minio/v2/metrics/cluster
      auth:
        type: bearer
