app:
  name: LibreTranslate

apache:
  upstream-url:
    - path: /
      target: http://app:5000

favicons:
  default: /static/favicon.ico

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer
  endpoints:
    - path: /metrics
      authentication:
        basic: prometheus

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
