app:
  name: OpenSpeedTest

apache:
  upstream-url:
    - path: /
      target: http://app:3000 # HTTPS endpoint is also available, but plain HTTP results in better performance

favicons:
  default: /assets/images/icons/apple-touch-icon.png
  # ico: /assets/images/icons/favicon-32x32.png

gatus:
  enabled: true
  conditions:
    - "[CONNECTED] == true"
    - "[STATUS] == 200"

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
