app:
  name: OpenSpeedTest

apache:
  upstream-url:
    - path: /
      target: http://app:3000 # HTTPS endpoint is also available, but plain HTTP results in better performance

gatus:
  enabled: true
  conditions:
    - "[CONNECTED] == true"
    - "[STATUS] == 200"

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
