app:
  name: Kiwix

apache:
  upstream-url:
    - path: /
      target: http://app:8080

gatus:
  enabled: false
  authentication:
    basic: homelab-viewer

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
