app:
  name: NPM Cache

apache:
  upstream-url:
    - path: /
      target: http://app:8080

favicons:
  default: "@npm-cache.png"

gatus:
  enabled: true

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
