app:
  name: Docker Cache

apache:
  upstream-url:
    - path: /
      target: http://app:80

gatus:
  enabled: true
  endpoints:
    - path: /v2/_catalog
      conditions:
        - "[CONNECTED] == true"
        - "[STATUS] == 200"
        - "has([BODY].repositories) == true"

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
