apache:
  upstream-url:
    - path: /
      target: http://app:9090

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer
  endpoints:
    - path: /metrics
      authentication:
        basic: prometheus

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
