apache:
  upstream-url:
    - path: /
      target: http://app:3456

gatus:
  enabled: false
  endpoints:
    - path: /api/v1/metrics

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
