x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./dawarich/Dockerfile
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    environment:
      MODE: app
    tmpfs:
      - /home/homelab/.cache:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/app/db:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/app/tmp:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/public:/var/app/public:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/watched:/var/app/tmp/imports/watched:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/storage:/var/app/storage:rw
      # - ${DOCKER_COMPOSE_APP_PATH}/app-data/postgis:/dawarich_db_data:rw # TODO: Determine if necessary

  sidekiq:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: template
    # Override:
    build:
      dockerfile: ./dawarich/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-sidekiq
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    environment:
      MODE: sidekiq
      PROMETHEUS_EXPORTER_HOST: app
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sidekiq"]
      interval: 10s
      retries: 1
      start_period: 60s
      timeout: 5s
    image: ${DOCKER_COMPOSE_APP_NAME}-sidekiq:1.0.0
    tmpfs:
      # - /root/.cache/gem:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/app/db:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/app/tmp:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/public:/var/app/public:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/watched:/var/app/tmp/imports/watched:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/storage:/var/app/storage:rw

  redis:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: redis
    # Override:
    # volumes:
    #   - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/shared:/data:rw # TODO: Determine if necessary

  postgis:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: postgis
    # Override:
    environment:
      POSTGRES_DB: dawarich

  decryptor:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./owntracks-decryptor/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-decryptor
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/decryptor.env
    image: ${DOCKER_COMPOSE_APP_NAME}-decryptor:1.0.0

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    # Override:
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/prometheus.htpasswd:/homelab/users/prometheus.htpasswd:ro

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
