app:
  name: Dozzle

apache:
  upstream-url:
    - path: /
      target: http://app:8080

favicons:
  default: /favicon.png
  # ico: /favicon.ico

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
