app:
  name: Gotify

apache:
  upstream-url:
    - path: /
      target: http://app:80

favicons:
  default: /static/favicon-196x196.png
  # ico: /static/favicon-32x32.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
