[global]
    # General
    map to guest = bad user
    server role = standalone server
    usershare max shares = 0
    # Logging
    log file = /var/log/samba/smbd.log
    max log size = 0
    log level = 1
    # SMB version
    server min protocol = SMB3_11
    server max protocol = SMB3_11
    # Better authentication
    ntlm auth = ntlmv2-only
    # Ignore junk files
    veto files = /._*/.DS_Store/.AppleDouble/.Trashes/.Trash/.AppleDB/.AppleDesktop/.TemporaryItems/.localized/thumbs.db/Thumbs.db/.windows/.mac/
    delete veto files = yes
    hide files = /.zfs/

[#smb-title#]
    path = /data/
    read only = no
    browseable = yes
    writeable = yes
    guest ok = no
    # Permitted users
    valid users = #smb-user#
    write list = #smb-user#
    admin users = #smb-user#
    # Force correct owner and permissions on disk
    force user = homelab
    force group = homelab
    inherit owner = yes
    create mask = 0664
    directory mask = 0775
