apache:
  upstream-url:
    - path: /
      target: http://app:8096

gatus:
  enabled: true
  additional_ports:
    http:
      - 8096
  endpoints:
    - path: /health
      body:
        - "[BODY] == Healthy"
    - path: /metrics
      authentication:
        basic: prometheus

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
