apache:
  upstream-url:
    - path: /
      target: http://app:8096

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
