app:
  name: Ntfy

apache:
  upstream-url:
    - path: /
      target: http://app:80

favicons:
  default: /static/images/apple-touch-icon.png
  # ico: /static/images/favicon.ico

gatus:
  enabled: true
  type: [http, smtp]
  additional_ports:
    tcp:
      - 25
  endpoints:
    - path: /v1/health

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
