- name: Sync secrets
  hosts: servers
  tasks:
    - name: Ping
      ansible.builtin.ping:

    ## Sync secrets ##

    - name: Sync SOPS config
      ansible.builtin.copy:
        src: "{{ repo_root }}/secrets/.sops.yml"
        dest: "{{ ansible_env.HOME }}/git/homelab/secrets/.sops.yml"

    - name: Sync private key
      ansible.builtin.copy:
        src: "{{ repo_root }}/secrets/age-key.txt"
        dest: "{{ ansible_env.HOME }}/git/homelab/secrets/age-key.txt"

    - name: Sync encrypted secrets
      ansible.builtin.copy:
        src: "{{ repo_root }}/secrets/secrets.enc.yml"
        dest: "{{ ansible_env.HOME }}/git/homelab/secrets/secrets.enc.yml"
