- name: Sync secrets
  hosts: servers
  tasks:
    - name: Ping
      ansible.builtin.ping:

    ## Sync secrets ##

    - name: Sync SOPS config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../secrets/{{ item.file }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/git/homelab/secrets/{{ item.file }}"
      loop:
        - file: ".sops.yml"
        - file: "key.txt"
        - file: "secrets.enc.yml"
