- name: Sync secrets
  hosts: servers
  tasks:
    - name: Ping
      ansible.builtin.ping:

    ## Sync secrets ##

    - name: Sync secrets
      register: sync_secrets
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../secrets/{{ item.file }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/git/homelab/secrets/{{ item.file }}"
      loop:
        - file: ".sops.yml"
        - file: "key.txt"
        - file: "secrets.enc.yml"

    - name: Update secrets
      register: update_secrets
      when: sync_secrets.changed
      changed_when: "'CHANGED' in update_secrets.stdout"
      ansible.builtin.shell: |
        set -eufo pipefail
        source "$HOME/.profile"

        cd "$HOME/git/homelab/servers/.current"
        before_sha="$(find . -path "./docker-apps/*/app-secrets/*" -type f -exec shasum {} \; 2>/dev/null | shasum)"

        task --taskfile './Taskfile.yml' secrets

        after_sha="$(find . -path "./docker-apps/*/app-secrets/*" -type f -exec shasum {} \; 2>/dev/null | shasum)"
        if [ "$before_sha" != "$after_sha" ]; then
          printf 'CHANGED\n'
        fi
