- name: Update system
  hosts: servers
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Update APT index
      when: ansible_facts['system'] == 'Linux' and ansible_facts['os_family'] == 'Debian'
      become: true
      ansible.builtin.apt:
        update_cache: true

    # Just a note, this can take a long time, especially on first run
    - name: Update APT packages
      when: ansible_facts['system'] == 'Linux' and ansible_facts['os_family'] == 'Debian'
      become: true
      ansible.builtin.apt:
        upgrade: true
        autoclean: true
        autoremove: true

    - name: Update NPM packages
      become: true
      community.general.npm:
        global: true
        state: latest

    - name: Update Pipx packages
      register: update_pipx
      changed_when: "'No packages upgraded' not in update_pipx.stdout"
      ansible.builtin.shell: |
        set -eufo pipefail
        source "$HOME/.profile"

        pipx upgrade-all

    - name: Update homelab repository
      register: update_git_homelab
      changed_when: "'CHANGED' in update_git_homelab.stdout"
      ansible.builtin.shell: |
        set -eufo pipefail
        source "$HOME/.profile"

        if [ -d "$HOME/git/homelab" ]; then
          cd "$HOME/git/homelab"
        else
          printf 'Directory ~/git/homelab not found\n'
          exit 1
        fi

        if [ "$(git branch --show-current)" != 'main' ]; then
          git checkout main
          printf 'CHANGED\n'
        fi

        if [ "$(git status --short)" != '' ]; then
          git checkout .
          git clean -df
          printf 'CHANGED\n'
        fi

        git fetch

        if [ "$(git diff --name-only origin/main)" != '' ]; then
          git pull --ff-only
          printf 'CHANGED\n'
        fi

    ## Sync secrets ##

    - name: Sync secrets
      register: sync_secrets
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../secrets/{{ item.file }}"
        dest: "{{ ansible_facts['env']['HOME'] }}/git/homelab/secrets/{{ item.file }}"
      loop:
        - file: ".sops.yml"
        - file: "key.txt"
        - file: "secrets.enc.yml"

    - name: Update secrets
      register: update_secrets
      when: sync_secrets.changed
      changed_when: "'CHANGED' in update_secrets.stdout"
      ansible.builtin.shell: |
        set -eufo pipefail
        source "$HOME/.profile"

        cd "$HOME/git/homelab/servers/.current"
        before_sha="$(find . -path "./docker-apps/*/app-secrets/*" -type f -exec shasum {} \; 2>/dev/null | shasum)"

        task secrets

        after_sha="$(find . -path "./docker-apps/*/app-secrets/*" -type f -exec shasum {} \; 2>/dev/null | shasum)"
        if [ "$before_sha" != "$after_sha" ]; then
          printf 'CHANGED\n'
        fi
