x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./homepage/Dockerfile
    dns: # Use internal DNS
      - 10.1.12.6
      - 10.1.10.6
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    networks:
      internal-network: {}
      external-network: {}
    tmpfs:
      - /app/.next/server/pages:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /app/config:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/homepage/default:/app/config/logs:rw

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    # Override:
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/users-admins.htpasswd:/homelab/users/users-admins.htpasswd:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/users-viewers.htpasswd:/homelab/users/users-viewers.htpasswd:ro

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

  widgets:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: template
    # Override:
    build:
      dockerfile: ./homepage-widgets/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-widgets
    dns: # Use internal DNS
      - 10.1.12.6
      - 10.1.10.6
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/widgets.env
    image: ${DOCKER_COMPOSE_APP_NAME}-widgets:1.0.0
    networks: # Network access is necessary for accessing other services via HTTPS
      internal-network: {}
      external-network: {}

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
