app:
  name: PiHole [blackhole]

apache:
  upstream-url:
    - path: /metrics
      target: http://app-prometheus-exporter:9617/metrics
    - path: /
      target: http://app:80

favicons:
  default: /admin/img/favicons/apple-touch-icon.png
  # ico: /admin/img/favicons/favicon-32x32.png

gatus:
  enabled: true
  type: [dns, http]
  endpoints:
    - path: /metrics
      authentication:
        basic: prometheus

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
