x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./certbot/Dockerfile
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    networks: # Internet access required for getting new Let's Encrypt certificate
      - external-network
      - internal-network
    tmpfs:
      - /etc/letsencrypt:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/lib/letsencrypt:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/certbot/data:/homelab/data:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/certs:/homelab/certs:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/certbot/default:/homelab/logs:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/certbot/letsencrypt:/var/log/letsencrypt:rw

  file-server:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: file-server
    # Override:
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/certbot/data:/homelab/www/download:rw

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    # Override:
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/users-admins.htpasswd:/homelab/users/users-admins.htpasswd:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/users-viewers.htpasswd:/homelab/users/users-viewers.htpasswd:ro

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
