app:
  name: Certbot

apache:
  upstream-url:
    - path: /
      target: http://file-server:8080

favicons:
  default: "@certbot.png"

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer

healthchecks:
  - slug: app
    schedule: "30 0 * * *"

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
