app:
  name: Certbot

apache:
  upstream-url:
    - path: /
      target: http://file-server:8080

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer

healthchecks:
  - slug: app
    schedule: "30 00 * * *"

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
