app:
  name: Ollama

apache:
  upstream-url:
    - path: /
      target: http://app:11434

gatus:
  enabled: true
  authentication:
    basic: homelab-viewer

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
