apache:
  upstream-url:
    - path: /api/
      target: http://app-backend:3333
    - path: /couchdb/
      target: http://couchdb:5984
    - path: /
      target: http://app-frontend:8100

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
