x-definitions: {}

services:
  app-frontend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-frontend
    image: ${DOCKER_COMPOSE_APP_NAME}-app-frontend:1.0.0
    build:
      dockerfile: ./external/adventurelog/frontend/Dockerfile
    environment:
      ORIGIN: ${DOCKER_COMPOSE_NETWORK_URL}

  app-backend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-backend
    image: ${DOCKER_COMPOSE_APP_NAME}-app-backend:1.0.0
    build:
      dockerfile: ./external/adventurelog/backend/Dockerfile
    environment:
      CSRF_TRUSTED_ORIGINS: ${DOCKER_COMPOSE_NETWORK_URL},${DOCKER_COMPOSE_NETWORK_URL_2}
      DJANGO_ADMIN_EMAIL: django@${DOCKER_COMPOSE_NETWORK_DOMAIN}
      FRONTEND_URL: ${DOCKER_COMPOSE_NETWORK_URL}
      PUBLIC_URL: ${DOCKER_COMPOSE_NETWORK_URL_2}
      DEFAULT_FROM_EMAIL: system@${DOCKER_COMPOSE_NETWORK_DOMAIN}
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app-backend.env
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/adventurelog/backend/data:/code/media:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/adventurelog/backend/nginx:/var/log/nginx:rw
    tmpfs:
      - /run:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/lib/nginx:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    # Internet access necessary for downloading data from raw.githubusercontent.com
    networks:
      internal-network: {}
      external-network: {}

  postgis:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: postgis
    environment:
      POSTGRES_DB: adventurelog

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache-frontend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-frontend
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-frontend:1.0.0
    environment:
      HOMELAB_CONTAINER_VARIANT: frontend
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache/frontend:/homelab/logs:rw

  apache-prometheus-exporter-frontend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-frontend
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-frontend:1.0.0
    environment:
      HOMELAB_CONTAINER_VARIANT: frontend
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache-prometheus-exporter/frontend:/homelab/logs:rw

  apache-backend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-backend
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-backend:1.0.0
    environment:
      HOMELAB_CONTAINER_VARIANT: backend
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache/backend:/homelab/logs:rw

  apache-prometheus-exporter-backend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-backend
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter-backend:1.0.0
    environment:
      HOMELAB_CONTAINER_VARIANT: backend
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache-prometheus-exporter/backend:/homelab/logs:rw

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
