x-definitions: {}

services:
  app-frontend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-frontend
    image: ${DOCKER_COMPOSE_APP_NAME}-app-frontend:1.0.0
    build:
      dockerfile: ./docker-images/adventurelog/frontend/Dockerfile
    environment:
      ORIGIN: ${DOCKER_COMPOSE_NETWORK_URL}

  app-backend:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./docker-images/adventurelog/backend/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-backend
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app-backend.env
    environment:
      CSRF_TRUSTED_ORIGINS: ${DOCKER_COMPOSE_NETWORK_URL}
      DEFAULT_FROM_EMAIL: system@${DOCKER_COMPOSE_NETWORK_DOMAIN}
      DJANGO_ADMIN_EMAIL: django-admin@${DOCKER_COMPOSE_NETWORK_DOMAIN}
      FRONTEND_URL: ${DOCKER_COMPOSE_NETWORK_URL}
      PUBLIC_URL: ${DOCKER_COMPOSE_NETWORK_URL}/api
    image: ${DOCKER_COMPOSE_APP_NAME}-app-backend:1.0.0
    networks: # Internet access necessary for downloading data from raw.githubusercontent.com
      - external-network
      - internal-network
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/adventurelog/data:/code/media:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/adventurelog/backend/nginx:/var/log/nginx:rw
    tmpfs:
      - /run:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/lib/nginx:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  postgis:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: postgis
    # Override:
    environment:
      POSTGRES_DB: adventurelog

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_NAME}-internal-network
    driver: bridge
    internal: true
