app:
  name: AdventureLog

apache:
  upstream-url:
    - path: /accounts/
      target: http://app-backend:80/accounts
    - path: /admin/
      target: http://app-backend:80/admin
    - path: /media/
      target: http://app-backend:80/media
    - path: /static/
      target: http://app-backend:80/static
    - path: /
      target: http://app-frontend:3000

favicons:
  default: /favicon.png

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
