app:
  nice-name: Git Cache

apache:
  upstream-url:
    - path: /
      target: http://app:8080

gatus:
  enabled: true

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
