servers:
  hosts:
    odroid-h3:
      ansible_host: server-odroid-h3.matejhome.com
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    odroid-h4-ultra:
      ansible_host: server-odroid-h4-ultra.matejhome.com
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-2g:
      ansible_host: server-raspberry-pi-4b-2g.matejhome.com
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    raspberry-pi-4b-4g:
      ansible_host: server-raspberry-pi-4b-4g.matejhome.com
      ansible_ssh_user: homelab
      ansible_shell_executable: /usr/bin/bash
    # macbook-pro-2012:
    #   ansible_host: server-macbook-pro-2012.matejhome.com
    #   ansible_ssh_user: homelab
    #   ansible_shell_executable: /usr/bin/bash

empty:
  hosts:
