app:
  name: Uptime Kuma

apache:
  upstream-url:
    - path: /
      target: http://app:3001

gatus:
  enabled: true
  endpoints:
    - path: /metrics
      authentication:
        basic: matej

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
        user: matej
