---
title: Docker Cache Proxy
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    class home_network dashed_border
    other_devices["<img src='../../../../icons/servers.png' style='min-width:80px;max-width:80px' /><br />Other<br />Devices"]
    class other_devices dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        docker_registry("<img src='../../../../icons/docker.png' style='min-width:80px;max-width:80px' /><br />Docker<br />Registry")

        socket_proxy <--->|:80,443| http_proxy <--->|:80| docker_registry
        http_proxy -..-|fs| certificate_manager
    end

    dockerhub["<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/cloud.png' style='min-width:100%;max-width:100%' /><img src='../../../../icons/docker.png' style='min-width:50px;max-width:50px;position:absolute;bottom:0;right:0' /></div><br />Public<br />container<br />registry"]
    class dockerhub dashed_border

    home_network <-->|:80,443| socket_proxy
    other_devices -..->|use| app_wrapper
    other_devices ~~~~ socket_proxy
    docker_registry -..->|use| dockerhub
