---
title: Dozzle agent
config:
    theme: dark
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.1em'><img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' /></div>Home<br/>Network"]
    class home_network dashed_border

    subgraph app_wrapper["Docker"]
        network_interface(" ")
        dozzle_agent("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/dozzle.png' style='min-width:80px;max-width:80px' /></div>Dozzle<br/>agent")

        network_interface --->|:7007|dozzle_agent
    end

    home_network <---> app_wrapper
