---
title: Gotify
config:
    theme: dark
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;
    classDef strong_border stroke-width:6px;

    subgraph others_1["Others"]
        home_network("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.1em'><img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' /></div>Home<br/>Network")
        prometheus("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/prometheus.png' style='min-width:80px;max-width:80px' /></div>Prometheus")
        gatus("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/gatus.png' style='min-width:80px;max-width:80px' /></div>Gatus")
    end

    subgraph app_wrapper["App"]
        inbound_interface(" ")
        apache_proxy("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /></div>Apache<br/>proxy")
        apache_prometheus_exporter("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/apache-prometheus-exporter.png' style='min-width:80px;max-width:80px' /></div>Apache<br/>prometheus<br/>exporter")
        certificator("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:1em'><img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /></div>Certificator")
        gotify("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/gotify.png' style='min-width:80px;max-width:80px' /></div>Gotify")
        class gotify strong_border;
        squid_proxy("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/squid.png' style='min-width:80px;max-width:80px' /></div>Squid<br/>proxy")
        squid_prometheus_exporter("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/squid-prometheus-exporter.png' style='min-width:80px;max-width:80px' /></div>Squid<br/>prometheus<br/>exporter")
        outbound_interface_1(" ")
        outbound_interface_2(" ")

        inbound_interface --->|:80,443| apache_proxy --->|:80| gotify
        apache_proxy -->|/.apache/metrics| apache_prometheus_exporter -.->|use status| apache_proxy
        apache_proxy -.-|fs| certificator
        outbound_interface_1 & outbound_interface_2 -..- squid_proxy
        apache_proxy -->|/.squid/metrics| squid_prometheus_exporter -.->|use| squid_proxy
    end

    home_network <--> inbound_interface
    prometheus -->|collect metrics| inbound_interface
    gatus -->|monitor| inbound_interface

    subgraph others_2["Others"]
        healthchecks("<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.5em'><img src='../../../../icons/healthchecks.png' style='min-width:80px;max-width:80px' /></div>Healthchecks")
        unknown("???")
    end

    squid_prometheus_exporter ~~~ others_2
    certificator --> outbound_interface_1 -->|report status| healthchecks
    gotify --> outbound_interface_2 -->|notifications| unknown
