---
title: Healthchecks
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    class home_network dashed_border
    other_apps["<img src='../../../../icons/apps.png' style='min-width:80px;max-width:80px' /><br />Other<br />Apps"]
    class other_apps dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        healthchecks("<img src='../../../../icons/healthchecks.png' style='min-width:80px;max-width:80px' /><br />Healthchecks")
        db_sync("<img src='../../../../icons/litestream.png' style='min-width:80px;max-width:80px' /><br />Litestream")

        socket_proxy <--->|:80,443| http_proxy <--->|:8000| healthchecks
        http_proxy -..-|fs| certificate_manager
        healthchecks ~~~ db_sync -..->|fs| healthchecks
    end

    s3_database["<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Minio"]
    class s3_database dashed_border

    home_network <--->|:80,443| socket_proxy
    other_apps -..->|send cron job status| app_wrapper
    other_apps ~~~~ socket_proxy
    db_sync -.->|send| s3_database
