---
title: Home Assistant
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.1em'><img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' /></div>Home<br />Network"]
    class home_network dashed_border
    smart_home_equipment["<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:1.5em'><img src='../../../../icons/home.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/iot.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-15px;right:0' /></div>Smart<br />Home"]
    class smart_home_equipment dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        home_assistant("<img src='../../../../icons/home-assistant.png' style='min-width:80px;max-width:80px' /><br />Home<br />Assistant")
        script_backup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/chromium.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/playwright.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-10px;right:-5px' /></div><br />Backup<br />script")

        socket_proxy <--->|:80,443| http_proxy <--->|:8123| home_assistant
        http_proxy -..-|fs| certificate_manager
        home_assistant ~~~ script_backup -..->|use| home_assistant
    end

    s3_database["<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.75em'><img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /></div>Minio"]
    class s3_database dashed_border

    home_network <--->|:80,443| socket_proxy
    smart_home_equipment <-..->|use/control| app_wrapper
    smart_home_equipment ~~~~ socket_proxy
    script_backup -.->|send backup| s3_database
