---
title: Lamp Controller
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    class home_network dashed_border
    home_assistant["<img src='../../../../icons/home-assistant.png' style='min-width:80px;max-width:80px' /><br />Home<br />Assistant"]
    class home_assistant dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        lamp_network_server("<img src='../../../../icons/placeholder.png' style='min-width:80px;max-width:80px' /><br />Lamp<br />API<br />server")
        lamp_hardware_controller("<img src='../../../../icons/placeholder.png' style='min-width:80px;max-width:80px' /><br />Lamp<br />GPIO<br />Controller")

        socket_proxy <--->|:80,443| http_proxy <--->|:80| lamp_network_server <--->|:80| lamp_hardware_controller
        http_proxy -..-|fs| certificate_manager
    end

    gpio_button("<img src='../../../../icons/button.png' style='min-width:80px;max-width:80px' /><br />GPIO<br />Button")
    class gpio_button dashed_border
    gpio_lamp("<img src='../../../../icons/lightbulb.png' style='min-width:80px;max-width:80px' /><br />GPIO<br />Lamp")
    class gpio_lamp dashed_border

    lamp_hardware_controller ~~~ gpio_button --->|control| lamp_hardware_controller
    lamp_hardware_controller --->|control| gpio_lamp

    home_network <-->|:80,443| socket_proxy
    home_assistant ~~~ socket_proxy
    home_assistant -..->|use| app_wrapper
