---
title: MinIO
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />network"]
    class home_network dashed_border
    other_apps["<img src='../../../../icons/apps.png' style='min-width:80px;max-width:80px' /><br />Other<br />apps"]
    class other_apps dashed_border

    subgraph app_wrapper[" "]
        socket_proxy_1("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        socket_proxy_2("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy_1("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        http_proxy_2("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        minio("<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />MinIO")
        minio_setup("<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Setup<br />script")

        socket_proxy_1 <--->|:80,443| http_proxy_1 <--->|:9000| minio
        socket_proxy_2 <--->|:80,443| http_proxy_2 <--->|:9001| minio
        http_proxy_1 & http_proxy_2 -..-|fs| certificate_manager
        minio ~~~ minio_setup -..->|use| minio
    end

    home_network <-->|:80,443| socket_proxy_1 & socket_proxy_2
    other_apps -..->|use| app_wrapper
    other_apps ~~~~ socket_proxy_2
