---
title: Omada Controller
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<div style='position:relative;width:80px;height:80px;margin:0 auto;margin-bottom:0.1em'><img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' /></div>Home<br />Network"]
    class home_network dashed_border
    tp_link_equipment["<img src='../../../../icons/tp-link.png' style='min-width:80px;max-width:80px' /><br />TP Link<br />Equipment"]
    class tp_link_equipment dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy_1("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        http_proxy_2("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        omada_controller("<img src='../../../../icons/tp-link-omada.png' style='min-width:80px;max-width:80px' /><br />Omada<br />Controller")
        script_backup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/chromium.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/playwright.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-10px;right:-5px' /></div><br />Backup<br />script")

        socket_proxy <--->|:80,443| http_proxy_1 <--->|:443| omada_controller
        socket_proxy <--->|:81,444| http_proxy_2 <--->|:444| omada_controller
        socket_proxy <--->|:27001,29810-29816| omada_controller
        http_proxy_1 & http_proxy_2 -..-|fs| certificate_manager
        omada_controller ~~~ script_backup -..->|use| omada_controller
    end

    s3_database["<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Minio"]
    class s3_database dashed_border

    home_network <--->|:80,81,443,444,27001,29810-29816| socket_proxy
    tp_link_equipment <-..->|use/control| app_wrapper
    tp_link_equipment ~~~~ socket_proxy
    script_backup -.->|send backup| s3_database
