---
title: PiHole
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' /><br />Home<br />Network"]
    class home_network dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        pihole("<img src='../../../../icons/pihole.png' style='min-width:80px;max-width:80px' /><br />PiHole")
        pihole_setup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/pihole.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/bash.png' style='min-width:40px;max-width:40px;position:absolute;bottom:-10px;right:0' /></div><br />Setup<br />script")
        script_backup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/chromium.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/playwright.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-10px;right:-5px' /></div><br />Backup<br />script")

        socket_proxy <--->|:80,443| http_proxy <--->|:80| pihole
        socket_proxy <--->|:53| pihole
        pihole ~~~ script_backup -..->|use| pihole
        pihole ~~~ pihole_setup -..->|fs| pihole
        http_proxy -..-|fs| certificate_manager
    end

    public_dns["<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/cloud.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/dns.png' style='min-width:40px;max-width:40px;position:absolute;bottom:10px;right:0' /></div>Public<br />DNS"]
    class public_dns dashed_border
    s3_database["<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Minio"]
    class s3_database dashed_border

    home_network <-->|:53,80,443| socket_proxy
    pihole_setup ~~~ public_dns
    pihole -..->|DNS queries| public_dns
    script_backup -.->|send backup| s3_database
