---
title: Uptime Kuma
---

flowchart LR
    classDef cluster fill:#ffffff00,stroke:#aabbccff,stroke-width:3px,rx:8px,ry:8px;
    classDef node fill:#ffffff00,stroke:#aabbccff,stroke-width:2px,rx:5px,ry:5px;
    classDef dashed_border stroke-dasharray:10 6;

    home_network["<img src='../../../../icons/network.png' style='min-width:80px;max-width:80px' />Home<br />Network"]
    class home_network dashed_border

    subgraph app_wrapper[" "]
        socket_proxy("<img src='../../../../icons/ingress.png' style='min-width:80px;max-width:80px' /><br />Socat")
        http_proxy("<img src='../../../../icons/apache.png' style='min-width:80px;max-width:80px' /><br />Apache")
        certificate_manager("<img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/lets-encrypt.png' style='min-width:80px;max-width:80px' /><br />Certificate<br />Manager")
        uptime_kuma("<img src='../../../../icons/uptime-kuma.png' style='min-width:80px;max-width:80px' /><br />Uptime<br />Kuma")
        script_backup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/chromium.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/cronjob.png' style='min-width:32px;max-width:32px;position:absolute;top:0;right:0' /><img src='../../../../icons/playwright.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-10px;right:-5px' /></div><br />Backup<br />script")
        script_admin_setup("<div style='position:relative;width:80px;height:80px;margin:0 auto'><img src='../../../../icons/chromium.png' style='min-width:80px;max-width:80px' /><img src='../../../../icons/playwright.png' style='min-width:48px;max-width:48px;position:absolute;bottom:-10px;right:-5px' /></div><br />Admin<br />setup<br />script")

        socket_proxy <--->|:80,443| http_proxy <--->|:3001| uptime_kuma
        uptime_kuma ~~~ script_backup & script_admin_setup -..->|use| uptime_kuma
        http_proxy -..-|fs| certificate_manager
    end

    other_apps["<img src='../../../../icons/apps.png' style='min-width:80px;max-width:80px' /><br />Other<br />Apps"]
    class other_apps dashed_border
    s3_database["<img src='../../../../icons/minio.png' style='min-width:80px;max-width:80px' /><br />Minio"]
    class s3_database dashed_border

    home_network <--->|:80,443| socket_proxy
    script_admin_setup ~~~ other_apps
    script_backup -.->|send backup| s3_database
    uptime_kuma -..->|check| other_apps
