x-definitions: {}

services:
  # This template should only be used for services which need host network
  template_no_network:
    build:
      args:
        GID: ${DOCKER_COMPOSE_GID}
        HOMELAB_APP_EXTERNAL_DOMAIN: ${DOCKER_COMPOSE_NETWORK_DOMAIN}
        HOMELAB_APP_EXTERNAL_IP: ${DOCKER_COMPOSE_NETWORK_IP}
        HOMELAB_APP_EXTERNAL_URL: ${DOCKER_COMPOSE_NETWORK_URL}
        HOMELAB_APP_NAME: ${DOCKER_COMPOSE_APP_NAME}
        HOMELAB_APP_TYPE: ${DOCKER_COMPOSE_APP_TYPE}
        HOMELAB_BUILD_ENV: ${DOCKER_COMPOSE_ENV}
        HOMELAB_ENV: ${DOCKER_COMPOSE_ENV}
        UID: ${DOCKER_COMPOSE_UID}
      context: ${DOCKER_COMPOSE_REPOROOT_PATH}/
      dockerfile: ./docker-images/PLACEHOLDER/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-PLACEHOLDER
    dns_opt:
      - single-request
    environment:
      HOMELAB_APP_EXTERNAL_DOMAIN: ${DOCKER_COMPOSE_NETWORK_DOMAIN}
      HOMELAB_APP_EXTERNAL_IP: ${DOCKER_COMPOSE_NETWORK_IP}
      HOMELAB_APP_EXTERNAL_URL: ${DOCKER_COMPOSE_NETWORK_URL}
      HOMELAB_APP_NAME: ${DOCKER_COMPOSE_APP_NAME}
      HOMELAB_APP_TYPE: ${DOCKER_COMPOSE_APP_TYPE}
      HOMELAB_ENV: ${DOCKER_COMPOSE_ENV}
    image: ${DOCKER_COMPOSE_APP_NAME}-PLACEHOLDER:1.0.0
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  # General purpose service template
  template:
    extends:
      service: template_no_network
    # Override:
    networks:
      - internal-network
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
      net.ipv6.conf.all.disable_ipv6: 1
    userns_mode: host # TODO: Remove this

  app:
    extends:
      service: template
    # Override:
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app
    image: ${DOCKER_COMPOSE_APP_NAME}-app:1.0.0

  certificator:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/certificator/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-certificator
    dns: # Use internal DNS
      - 10.1.12.6
      - 10.1.10.6
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/certificator.env
    image: ${DOCKER_COMPOSE_APP_NAME}-certificator:1.0.0
    networks:
      - external-network
      - internal-network
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/certs:/homelab/certs:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/certificator/default:/homelab/logs:rw

  apache:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/apache/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache
    dns: # Use blackhole DNS
      - 10.1.12.7
      - 10.1.10.7
    image: ${DOCKER_COMPOSE_APP_NAME}-apache:1.0.0
    networks:
      - external-network # TODO: Connect to external world via socat instead
      - internal-network
    tmpfs:
      - /var/lock:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/log/apache2:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      - /var/run/apache2:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/certs:/homelab/certs:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/apache/default:/homelab/logs:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/proxy-status.htpasswd:/homelab/users/proxy-status.htpasswd:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/proxy-prometheus.htpasswd:/homelab/users/proxy-prometheus.htpasswd:ro

  apache-prometheus-exporter:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/apache-prometheus-exporter/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/apache-prometheus-exporter.env
    image: ${DOCKER_COMPOSE_APP_NAME}-apache-prometheus-exporter:1.0.0

  socket-proxy:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/socket-proxy/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-socket-proxy
    image: ${DOCKER_COMPOSE_APP_NAME}-socket-proxy:1.0.0
    tmpfs:
      - /run:rw,uid=0,gid=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  docker-app-setup:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/docker-setup/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-setup
    environment:
      DOCKER_HOST: tcp://socket-proxy:2375
      HOMELAB_SETUP_TARGET_CONTAINER: ${DOCKER_COMPOSE_APP_NAME}-app
    image: ${DOCKER_COMPOSE_APP_NAME}-app-setup:1.0.0
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  favicons:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/favicons/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-favicons
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/favicons.env
    image: ${DOCKER_COMPOSE_APP_NAME}-favicons:1.0.0

  file-server:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/file-server/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-file-server
    image: ${DOCKER_COMPOSE_APP_NAME}-file-server:1.0.0

  script-app-setup:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/script-setup/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-app-setup
    image: ${DOCKER_COMPOSE_APP_NAME}-app-setup:1.0.0
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}

  redis:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/redis/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-redis
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/redis.env
    image: ${DOCKER_COMPOSE_APP_NAME}-redis:1.0.0
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/redis/data:/data:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/redis/certs:/homelab/redis-certs:rw

  postgres:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/postgres/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-postgres
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgres.env
    image: ${DOCKER_COMPOSE_APP_NAME}-postgres:1.0.0
    shm_size: 1G
    tmpfs:
      - /var/run:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/postgres/data:/var/lib/postgresql/data:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgres.key:/homelab/certs/postgres.key:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgres.crt:/homelab/certs/postgres.crt:ro

  postgis:
    extends:
      service: template
    # Override:
    build:
      dockerfile: ./docker-images/postgis/Dockerfile
    container_name: ${DOCKER_COMPOSE_APP_NAME}-postgis
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgis.env
    image: ${DOCKER_COMPOSE_APP_NAME}-postgis:1.0.0
    shm_size: 1G
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-data/postgis/data:/var/lib/postgresql/data:rw
      # - ${DOCKER_COMPOSE_APP_PATH}/app-data/dawarich/shared:/var/shared:rw # TODO: Determine if necessary
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgres.key:/homelab/certs/postgres.key:ro
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/postgres.crt:/homelab/certs/postgres.crt:ro
    tmpfs:
      - /var/run:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
