app:
  name: Unifi Controller

apache:
  upstream-url:
    - path: /
      target: https://app:8443

gatus:
  enabled: true
  additional_ports:
    tcp:
      - 6789
  endpoints:
    - path: /status
    - path: :8080
      protocol: http
      insecure: true
      conditions:
        - "[CONNECTED] == true"
        - "[STATUS] == 200"
    - path: :8443
      insecure: true
      conditions:
        - "[CONNECTED] == true"
        - "[STATUS] == 200"

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
