app:
  name: NoVNC

apache:
  upstream-url:
    - path: /
      target: http://app:6080

favicons:
  default: /app/images/icons/novnc-ios-180.png
  # ico: /app/images/icons/novnc.ico

gatus:
  enabled: true

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
