name: Make Build

permissions: {}

on:
  pull_request:

jobs:
  build:
    name: Make Build
    runs-on: ubuntu-latest
    env:
      COMPOSE_BAKE: "true"
      COMPOSE_DOCKER_CLI_BUILD: "1"
      DOCKER_BUILDKIT: "1"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4.2.0
        with:
          version: latest
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.path }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.path }}

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v2.3.0
        with:
          version: latest

      - name: Install APT dependencies
        run: |
          set -euf
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends --no-install-suggests apache2-utils moreutils

      - name: Setup Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: 3.x

      - name: Setup NodeJS
        uses: actions/setup-node@v7.0.0
        with:
          node-version: latest

      - name: Install NodeJS dependencies
        run: |
          set -euf
          printf 'fetch-retries=5\nfetch-retry-factor=10\nfetch-retry-maxtimeout=60000\nfetch-retry-mintimeout=1000\nignore-scripts=true\nmin-release-age=1\n' >>"$HOME/.npmrc"
          NODE_OPTIONS=--dns-result-order=ipv4first npm install --unsafe-perm --no-progress --no-audit --no-fund --loglevel=error --prefer-offline --global @go-task/cli

      - name: Bootstrap dependencies
        run: |
          set -euf
          make bootstrap

      - name: Build
        run: |
          set -euf
          make build

      - name: Docker build
        run: |
          set -euf
          make docker-build
