name: Raw Build

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-build:
    name: Native Build
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Install APT dependencies
        run: |
          set -euf
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends --no-install-suggests apache2-utils moreutils

      - name: Setup NodeJS
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: actions/setup-node@v7.0.0
          attempt_limit: 3
          attempt_delay: 2500
          with: |
            node-version: latest

      - name: Setup Python
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: actions/setup-python@v7.0.0
          attempt_limit: 3
          attempt_delay: 2500
          with: |
            python-version: 3.x

      - name: Bootstrap dependencies
        run: |
          set -euf
          make bootstrap

      - name: Build
        run: |
          set -euf
          make build
