x-definitions: {}

services:
  app:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: app
    # Override:
    build:
      dockerfile: ./docker-images/samba/Dockerfile
      args:
        HOMELAB_SAMBA_CONFIG: ${DOCKER_COMPOSE_SAMBA_CONFIG}
    cap_add:
      - SETGID # Necessary for `su` to set supplementary groups
      - SETUID # Necessary for `su` to switch to the homelab user
      - SYS_PTRACE # Necessary to export prometheus metrics
    dns: # Use blackhole DNS
      - 10.1.12.7
      - 10.1.10.7
    env_file:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/app.env
    environment:
      SAMBA_TITLE: ${DOCKER_COMPOSE_NETWORK_DOMAIN}
    networks:
      - external-network
      - internal-network
    tmpfs:
      - /homelab/tmpfs:rw,noexec,nodev,noatime,nodiratime,uid=${DOCKER_COMPOSE_UID},gid=${DOCKER_COMPOSE_GID}
      # The below mounts are mounted as root, because samba runs as root
      - /run:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /run/samba:rw,noexec,nodev,noatime,nodiratime,mode=0755,uid=0,gid=0
      - /var/cache/samba:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/lib/samba:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/lib/samba/private:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/lib/samba/usershares:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/log/samba:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/log/samba_smbd:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/log/samba_statusd:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
      - /var/log/samba_exporter:rw,noexec,nodev,noatime,nodiratime,uid=0,gid=0
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/samba/smbd:/homelab/logs/samba_smbd:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/samba/statusd:/homelab/logs/samba_statusd:rw
      - ${DOCKER_COMPOSE_APP_PATH}/app-logs/samba/exporter:/homelab/logs/samba_exporter:rw

  certificator:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: certificator

  apache:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache
    volumes:
      - ${DOCKER_COMPOSE_APP_PATH}/app-secrets/prometheus.htpasswd:/homelab/users/prometheus.htpasswd:ro

  apache-prometheus-exporter:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: apache-prometheus-exporter

  favicons:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: favicons

  file-server:
    extends:
      file: ${DOCKER_COMPOSE_REPOROOT_PATH}/docker-compose/.shared/compose.yml
      service: file-server

networks:
  default:
    driver: none
  external-network:
    name: ${DOCKER_COMPOSE_APP_SHORTNAME}-external-network
    driver: bridge
    internal: false
  internal-network:
    name: ${DOCKER_COMPOSE_APP_SHORTNAME}-internal-network
    driver: bridge
    internal: true
