apache:
  upstream-url:
    - path: /metrics
      target: http://app:9922/metrics
    - path: /
      target: http://file-server:8080

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
