app:
  name: Samba

apache:
  upstream-url:
    - path: /metrics
      target: http://app:9922/metrics
    - path: /
      target: http://file-server:8080

gatus:
  enabled: true
  type: [http, smb]
  additional_ports:
    tcp:
      - 139
      - 445
  endpoints:
    - path: /metrics
      authentication:
        basic: prometheus

healthchecks:
  - slug: certificator

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
