app:
  nice-name: Home Assistant

apache:
  upstream-url:
    - path: /
      target: http://app:8123

gatus:
  enabled: true
  endpoints:
    - path: /api/prometheus
      authentication:
        bearer: PROMETHEUS_TOKEN

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /api/prometheus
      auth:
        type: bearer
