app:
  nice-name: Smtp4Dev

apache:
  upstream-url:
    - path: /
      target: http://app:5000

gatus:
  enabled: true
  type: [http, smtp]
  authentication:
    basic: homelab-viewer
  additional_ports:
    tcp:
      - 25

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
