apache:
  upstream-url:
    - path: /
      target: http://app:9100

prometheus:
  enabled: true
  endpoints:
    - path: /.apache/metrics
      auth:
        type: basic
    - path: /metrics
      auth:
        type: basic
